apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "master-chart.fullname" . }}
  labels:
    {{- include "master-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.application.autoscaling.enabled }}
  replicas: {{ .Values.application.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "master-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum: {{ include "checksum.secret" . }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "master-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.application.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "master-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "master-chart.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.application.image.repository }}:{{ .Values.application.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.application.command }}
          command:
            {{- toYaml .Values.application.command | nindent 12 }}
          {{- end }}
          {{- if .Values.application.args }}
          args:
            {{- toYaml .Values.application.args | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.application.image.pullPolicy }}
          ports:
          {{- range .Values.service.ports }}
          - name: {{ .name }}
            containerPort: {{ .port }}
            protocol: {{ .protocol }}
          {{- end }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "{{ .Values.application.preStopCommand }}"]
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          {{- toYaml .Values.application.envs | nindent 10 }}
          livenessProbe:
            {{- toYaml .Values.application.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.application.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.application.resources | nindent 12 }}
          {{- with .Values.application.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.application.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}