{{- if .Values.application.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ include "master-chart.fullname" . }}-hpa"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "master-chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "master-chart.fullname" . }}
  minReplicas: {{ .Values.application.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.application.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.application.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.application.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.application.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.application.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}