apiVersion: v1
kind: Service
metadata:
  name: "{{ include "master-chart.fullname" . }}-service"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "master-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "master-chart.selectorLabels" . | nindent 4 }}
